spring:
  datasource:
    url: jdbc:mysql://43.139.45.79:3306/school?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: school
    password: 1393844930ouliang
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
mybatis:

  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

